development1:
  adapter: oracle_enhanced
  database: orcl
  username: scott
  password: tiger  

development2:
  adapter: oracle_enhanced
  host: 10.162.106.154
  port: 1521
  database: orcl
  username: scott
  password: tiger
  
development_target:
  adapter: sqlite3
  database: development.sqlite3
  pool: 5
  timeout: 5000

test: 
  adapter: oracle 
  database: comics_catalog_test 
  username: comics_catalog 
  password: 

production: 
  adapter: oracle 
  database: comics_catalog_production  
  username: comics_catalog 
  password: