source:
  adapter: oracle_enhanced
  host: 10.162.211.9
  port: 1521
  database: ztjc2
  username: mw_ztjc
  password: ztjc

target:
  adapter: oracle_enhanced
  host: 10.162.106.153
  port: 1521
  database: orcl
  username: mw_app
  password: mw_app
  
test_target:
  adapter: sqlite3
  database: development.sqlite3
  pool: 5
  timeout: 5000

production: 
  adapter: oracle 
  database: comics_catalog_production  
  username: comics_catalog 
  password: